### PR TITLE
fix: 运行demo的时候，连接无线网，默认会获取IPv6 地址，导致报错

### PR DESCRIPTION
**Pull request by plan454**
修复在无线网环境下运行demo ，产生 Can't assign requested address 错误

### CODE REVIEW

**Comment by qinliujie** [comment]
@chickenlj that's ok,please review

**Comment by lliule** [comment]
@plan454 
我clone  dubbo-demo代码，运行的时候需要修改什么配置参数吗？
image
这个地址是什么意思？
还有我运行provider没有问题，在运行comsumer就报错：

[23/12/17 03:32:44:044 GMT+08:00] main  INFO support.ClassPathXmlApplicationContext: Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@c2e1f26: startup date [Sat Dec 23 15:32:44 GMT+08:00 2017]; root of context hierarchy
[23/12/17 03:32:44:044 GMT+08:00] main  INFO xml.XmlBeanDefinitionReader: Loading XML bean definitions from class path resource [META-INF/spring/dubbo-demo-consumer.xml]
[23/12/17 03:32:44:044 GMT+08:00] main  INFO logger.LoggerFactory: using logger: com.alibaba.dubbo.common.logger.log4j.Log4jLoggerAdapter
[23/12/17 03:32:45:045 GMT+08:00] main  INFO server.Server:  [DUBBO] qos-server bind localhost:33333, dubbo version: 2.0.0, current host: 127.0.0.1
[23/12/17 03:32:46:046 GMT+08:00] main  INFO multicast.MulticastRegistry:  [DUBBO] Register: consumer://192.168.99.1/com.alibaba.dubbo.demo.DemoService?application=demo-consumer&category=consumers&check=false&dubbo=2.0.0&interface=com.alibaba.dubbo.demo.DemoService&methods=sayHello&pid=19192&side=consumer&timestamp=1514014366115, dubbo version: 2.0.0, current host: 192.168.99.1
[23/12/17 03:32:46:046 GMT+08:00] main  INFO multicast.MulticastRegistry:  [DUBBO] Send broadcast message: register consumer://192.168.99.1/com.alibaba.dubbo.demo.DemoService?application=demo-consumer&category=consumers&check=false&dubbo=2.0.0&interface=com.alibaba.dubbo.demo.DemoService&methods=sayHello&pid=19192&side=consumer&timestamp=1514014366115 to /224.5.6.7:1234, dubbo version: 2.0.0, current host: 192.168.99.1
[23/12/17 03:32:46:046 GMT+08:00] main  INFO multicast.MulticastRegistry:  [DUBBO] Subscribe: consumer://192.168.99.1/com.alibaba.dubbo.demo.DemoService?application=demo-consumer&category=providers,configurators,routers&check=false&dubbo=2.0.0&interface=com.alibaba.dubbo.demo.DemoService&methods=sayHello&pid=19192&side=consumer&timestamp=1514014366115, dubbo version: 2.0.0, current host: 192.168.99.1
[23/12/17 03:32:46:046 GMT+08:00] DubboMulticastRegistryReceiver  INFO multicast.MulticastRegistry:  [DUBBO] Receive multicast message: register consumer://192.168.99.1/com.alibaba.dubbo.demo.DemoService?application=demo-consumer&category=consumers&check=false&dubbo=2.0.0&interface=com.alibaba.dubbo.demo.DemoService&methods=sayHello&pid=19192&side=consumer&timestamp=1514014366115 from /192.168.56.1:1234, dubbo version: 2.0.0, current host: 192.168.99.1
[23/12/17 03:32:46:046 GMT+08:00] main  INFO multicast.MulticastRegistry:  [DUBBO] Send broadcast message: subscribe consumer://192.168.99.1/com.alibaba.dubbo.demo.DemoService?application=demo-consumer&category=providers,configurators,routers&check=false&dubbo=2.0.0&interface=com.alibaba.dubbo.demo.DemoService&methods=sayHello&pid=19192&side=consumer&timestamp=1514014366115 to /224.5.6.7:1234, dubbo version: 2.0.0, current host: 192.168.99.1
[23/12/17 03:32:46:046 GMT+08:00] DubboMulticastRegistryReceiver  INFO multicast.MulticastRegistry:  [DUBBO] Receive multicast message: subscribe consumer://192.168.99.1/com.alibaba.dubbo.demo.DemoService?application=demo-consumer&category=providers,configurators,routers&check=false&dubbo=2.0.0&interface=com.alibaba.dubbo.demo.DemoService&methods=sayHello&pid=19192&side=consumer&timestamp=1514014366115 from /192.168.56.1:1234, dubbo version: 2.0.0, current host: 192.168.99.1
[23/12/17 03:32:47:047 GMT+08:00] main  WARN multicast.MulticastRegistry:  [DUBBO] Ignore empty notify urls for subscribe url consumer://192.168.99.1/com.alibaba.dubbo.demo.DemoService?application=demo-consumer&category=providers,configurators,routers&check=false&dubbo=2.0.0&interface=com.alibaba.dubbo.demo.DemoService&methods=sayHello&pid=19192&side=consumer&timestamp=1514014366115, dubbo version: 2.0.0, current host: 192.168.99.1
[23/12/17 03:32:47:047 GMT+08:00] main  INFO config.AbstractConfig:  [DUBBO] Refer dubbo service com.alibaba.dubbo.demo.DemoService from url multicast://224.5.6.7:1234/com.alibaba.dubbo.registry.RegistryService?application=demo-consumer&check=false&dubbo=2.0.0&interface=com.alibaba.dubbo.demo.DemoService&methods=sayHello&pid=19192&register.ip=192.168.99.1&side=consumer&timestamp=1514014366115, dubbo version: 2.0.0, current host: 192.168.99.1
com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method sayHello in the service com.alibaba.dubbo.demo.DemoService. No provider available for the service com.alibaba.dubbo.demo.DemoService from registry 224.5.6.7:1234 on the consumer 192.168.99.1 using the dubbo version 2.0.0. Please check if the providers have been started and registered.
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.checkInvokers(AbstractClusterInvoker.java:253)
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:55)
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:229)
	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:72)
	at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:51)
	at com.alibaba.dubbo.common.bytecode.proxy0.sayHello(proxy0.java)


我不是太明白，是不是注册的地址要写本地的ip？我修改成本地ip也报错

**Comment by plan454** [comment]
@lliule 报错显示的是找不到你本地的provder，你在启动consumer 的时候 启动provider了吗

**Comment by warriorSL2016** [comment]
我也遇到这个恶心的问题了, 使用   <dubbo:registry address="multicast://224.5.6.7:1234"/>, 运行官网实例的dubbo-demo项目, 并且还是使用提示的使用debug,或者配置-Djava.net.preferIPv4Stack=true, 防止使用ipv6, 服务方能正常启动, 但是消费方根本就找不到服务, 请给出解释, 浪费了很长时间....错误栈如下:

com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method sayHello in the service com.alibaba.dubbo.demo.DemoService. No provider available for the service com.alibaba.dubbo.demo.DemoService from registry 224.5.6.7:1234 on the consumer 192.168.2.110 using the dubbo version 2.0.0. Please check if the providers have been started and registered.
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.checkInvokers(AbstractClusterInvoker.java:252)
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:55)
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:233)
	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:70)
	at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:51)
	at com.alibaba.dubbo.common.bytecode.proxy0.sayHello(proxy0.java)
	at com.alibaba.dubbo.demo.consumer.Consumer.main(Consumer.java:35)

**Comment by startjava** [comment]
@warriorSL2016 这个问题解决了吗？

**Pull request merged**
