### PR TITLE
shutdown with count down latch

### PR DESCRIPTION
**Pull request by johnraychina**
Notify - wait mechanism is fragile,  Main.class is global, anyone could wait on or notify it, which makes shutdown fragile too.

Shutdown with count down latch can avoid evil notify on Main.class(which causes abnormal shutdown) or evil wait on Main.class(which causes non-stop).

### CODE REVIEW

**Comment by qinliujie** [comment]
@johnraychina I think it is better to put running.countDown() outside the for loop, how do you think?

**Comment by johnraychina** [comment]
@qinliujie Sometimes container.stop() may throw exceptions, 
it denpends on how you want shutdown the application: 
- I prefer to solve the exceptions, and shutdown again;
- If running.countDown() is outside of the loop,  main thread is stopped while container is still running, then the application is in a very strange status.

**Comment by bigcai** [comment]
why do Main.class start so many container? --" for( Container container: containers ) { .....}  
BUT the countDownLatch just count one

**Comment by johnraychina** [comment]
@bigcai 
Because Multiple containers is added AFTER my fork, and this branch is is conflict with master.

**Comment by johnraychina** [comment]
Since simple object lock will be ok to avoid evil wait on Main class, I 'll just create another pull request.

**Comment by chickenlj** [comment]
@johnraychina 
Current logic do have problem. 
1. Main.class.wait() may never receive a notify.
2. But because of `running` flag, i think the main process will not shutdown unexpectedly.

Looking forward to your new PR

**Comment by chickenlj** [comment]
I have fixed this, see [Fixed #520 change Main.class wait/notify to lock/condition
](https://github.com/alibaba/dubbo/commit/49af203aa20667a0568a19566c1e9892166435ae)

**Pull request closed without merging**
