### PR TITLE
[DUBBO-REST]merge dubbox's REST implementation 

### PR DESCRIPTION
**Pull request by Authorlove**
## What is the purpose of the change

support REST

## Brief changelog

1. merge REST implementation of DUBBOX
2. upgrade resteasy and its netty container

## Verifying this change
https://dangdangdotcom.github.io/dubbox/rest.html

### CODE REVIEW

**Comment by lovepoem** [comment]
https://github.com/alibaba/dubbo/pull/917

**Comment by superleo-cn** [comment]
这个合并除了Rest，是不是 Kryo和FST序列化都合并进来了。

**Comment by lovepoem** [comment]
>这个合并除了Rest，是不是 Kryo和FST序列化都合并进来了。
明显只有rest api.你可以看changes

**Comment by lovepoem** [comment]
>这个合并除了Rest，是不是 Kryo和FST序列化都合并进来了。

明显只有rest api.你可以看changes

**Comment by lovepoem** [comment]
https://github.com/alibaba/dubbo/pull/1001

**Comment by lovepoem** [comment]
#1001 was merge since https://github.com/alibaba/dubbo/releases/tag/dubbo-2.6.0

**Pull request closed without merging**
