### PR TITLE
添加REST协议的支持

### PR DESCRIPTION
**Pull request by li-shen**
添加REST协议的实现、例子和说明文档，同时为dubbo-remoting-http添加基于嵌入式tomcat的实现，升级了servlet版本，升级了httpclient版本，为RpcContext增加了简单的方法等，后面几个改动基本都是rest协议所需要的。

### CODE REVIEW

**Comment by Authorlove** [comment]
@li-shen we really appreciate your work on supporting rest! Could you please spend some time resolving the conflict?

**Comment by lovepoem** [comment]
https://github.com/alibaba/dubbo/issues/848

**Comment by Authorlove** [comment]
FYI 
I am trying to solve the conflicts now

**Comment by lovepoem** [comment]
https://github.com/alibaba/dubbo/pull/1001

**Comment by lovepoem** [comment]
#1001 was merge since https://github.com/alibaba/dubbo/releases/tag/dubbo-2.6.0

**Pull request closed without merging**
