### PR TITLE
Collection.isEmpty() should be used to test for emptiness

### PR DESCRIPTION
**Pull request by igor-suhorukov**
## What is the purpose of the change
Polish: use Collection.isEmpty()

## Brief changelog

Using Collection.size() to test for emptiness works, but using Collection.isEmpty() makes the code more readable and can be more performant. The time complexity of any isEmpty() method implementation should be O(1) whereas some implementations of size() can be O(n).

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [ ] Make sure there is a [GITHUB_issue](https://github.com/alibaba/dubbo/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/dubbo/tree/master/dubbo-test).
- [x] Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [x] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by chickenlj** [comment]
That's a good point, i will have a review on your changes later.

**Comment by ralf0131** [comment]
Hi, welcome to the Dubbo community and great works!

Few comments here:

> Using Collection.size() to test for emptiness works, but using Collection.isEmpty() makes the code more readable and can be more performant. 

+ 1 to the readability. 

> The time complexity of any isEmpty() method implementation should be O(1) whereas some implementations of size() can be O(n).

I am not convinced by the conclusion. In my assumption, testing isEmpty() should be no slower that testing size(), because we need the actual size of the collection before we know whether it is empty. I've checked at least ArrayList, LinkedList, CopyOnWriteList, HashMap, HashSet, TreeMap, ConcurrentHashMap, and there is is no violation. Could you give an example for that?

**Comment by igor-suhorukov** [comment]
@ralf0131 as an example ConcurrentLinkedQueue size complexity O(n), ConcurrentSkipListSet under the hood use ConcurrentSkipListMap with size complexity O(n)

**Comment by ralf0131** [comment]
@igor-suhorukov Thanks for your clarification! That make sense to me.

**Comment by beiwei30** [comment]
thanks for your PR, the change looks good.

**Pull request merged**
