### PR TITLE
Enhancement for graceful shutdown

### PR DESCRIPTION
**Pull request by manzhizhen**
## What is the purpose of the change

目前不管是用的最多的2.5.3版本还是最新的2.5.7版本，亲自测试在不设置重试机制下是无法做到优雅停机的，这次改动主要是修改一点点代码，加上可配置的等待时间，就能简单的做到“不开启重试也能优雅停机”。

其主要实现机制就是在【provider断连注册中心之后，关闭应答之前】和【consumer移除掉invoker后，关闭client之前】这两个阶段加入可配置的等待时间，目前亲测可以做到不配置重试也能优雅停机。

## Brief changelog

modified:   dubbo-common/src/main/java/com/alibaba/dubbo/common/Constants.java
modified:   dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/ProtocolConfig.java
modified:   dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/protocol/AbstractInvoker.java
modified:   dubbo-rpc/dubbo-rpc-default/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/DubboInvoker.java
modified:   dubbo-rpc/dubbo-rpc-thrift/src/main/java/com/alibaba/dubbo/rpc/protocol/thrift/ThriftInvoker.java

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/alibaba/dubbo/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/dubbo/tree/master/dubbo-test).
- [ ] Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by manzhizhen** [comment]
因为现在大多数用dubbo的公司，为了避免极端情况下的雪崩和流量风暴，大部分接口都会关闭重试机制，这样，对于当前dubbo优雅停机的设定，就无法做到优雅停机了，所以这里通过比较简单的方式，加大了在不重试情况下优雅停机的成功率。

http://blog.csdn.net/manzhizhen/article/details/78756370

**Comment by manzhizhen** [comment]
测试方案：
A模块（consumer，部署单个）高并发调用B模块（provider，部署多个）某个接口，然后对B模块进行kill，看A模块是否报错。

B模块配置和代码：	
```
<dubbo:application name="mzz-dubbo2"/>
<dubbo:protocol name="dubbo" port="8887" threads="200" dispatcher="message" />
<dubbo:registry id="dubboRegistry" protocol="zookeeper" address="127.0.0.1:2181"/>
<dubbo:provider token="true" connections="3"/>
<dubbo:service interface="com.manzhizhen.dubbo.service.Dubbo2Service"
			ref="dubbo2Service" version="1.0.0" timeout="100" />
<dubbo:service interface="com.manzhizhen.dubbo.service.Dubbo2Service1"
				   ref="dubbo2Service1" version="1.0.0" timeout="100" />
```

**Comment by manzhizhen** [comment]
改造前，如果创建1个A模块实例和5个B模块实例，在启动后，使用kill杀掉其中一个B模块，A模块将会产生如下异常：

**Comment by manzhizhen** [comment]
如果想调整provider和consumer的等待时间，只需要在dubbo.properties中设置如下key就可以：
provider.shutdown.min.wait=5000
consumer.shutdown.min.wait=2000

**Comment by manzhizhen** [comment]
@chickenlj  先给我点时间了解下49525b0，呵呵

**Comment by 1cming** [comment]
That's what I need !!!

**Pull request closed without merging**
