### PR TITLE
merge dubbox core features from dangdang:

### PR DESCRIPTION
**Pull request by terrymanu**
## What is the purpose of the change

merge dubbox core features

## Brief changelog

1. rest protocol
2. kryo & fst serialization
3. embed tomcat

### CODE REVIEW

**Comment by chickenlj** [comment]
We have been concerned about the awesome features in dubbox, thanks for making this contribution.
Are you an official partner of dubbox? Maybe we can issue an announcement separately, so both users of dubbo and dubbox can notice this change. We can continue to promote these features on the dubbo project.

**Comment by terrymanu** [comment]
@chickenlj Hello chickenlj. Yes, I am dubbox's official owner from dangdang. Thanks for alibaba open source dubbo, it is really a wonderful project.
It is a good idea to  issue an announcement separately after dubbo merge dubbox.

**Comment by zhangruhong** [comment]
火钳刘明

**Comment by chickenlj** [comment]
We decide to merge this part after version 2.5.8, which will be in the next few days.

**Comment by linyongfu2013** [comment]
so it should be coming soon ? looking forward to it .

**Comment by lovepoem** [comment]
https://github.com/alibaba/dubbo/issues/764

**Comment by kirbylynx** [comment]
Really looking forward for 2.5.8.
As far as I know, it would include two exciting features, REST/kryo/FST serialization, and spring boot starter support.

**Comment by fanlei1988** [comment]
真是个好消息，不过，我还是希望dubbo 同时也可以支持SpringMVC 的Rest实现， 因为我感觉dubbox 和swagger 兼容并不是很好，并且并不支持其他容器吧

**Comment by nmyphp** [comment]
太好了！作为当当员工，之前一直使用dubbox，得知dubbo重新维护了，第一个问题就是dubbox是否会继续更新，这下好了。会一直关注

**Comment by zuohl** [comment]
怎么pr还不合并,,还是说准备自己实现一套..

**Comment by chickenlj** [comment]
I decide to merge this PR to the 2.6 branch first, and do some adjust, e.g, upgrade dependency version.

**Comment by FredGoo** [comment]
持续关注中

**Comment by chickenlj** [comment]
The core features of this PR have been published in [2.6.0](https://github.com/alibaba/dubbo/releases/tag/dubbo-2.6.0)

**Comment by Lovelcp** [comment]
赞赞赞

**Comment by leontius** [comment]
关注中。

**Comment by PepperYan** [comment]
等了这么久终于合并了!

**Comment by zhenyajiang** [comment]
you should  metion about what's the version of kyro and FST dependency. it cause the problem. Caused by: java.lang.NoClassDefFoundError: com/esotericsoftware/kryo/pool/KryoFactory.
anyway, tks a lot for dangdang and alibaba open source.

**Comment by superleo-cn** [comment]
我在kryo基础上还加入了twitter chill，支持Java的同时，还能比较完美的支持Scala，让Scala童鞋也能享受dubbo直接支持数据类型的快感，如何分享呢？

**Comment by luzhzhsoft** [comment]
有没有rest 的demo 或者相关的文档介绍呐？按照当当的demo 跑不起来。好像是kryo 版本的问题

**Comment by nmyphp** [comment]
@luzhzhsoft可以参考一下这篇CSDN博客：https://blog.csdn.net/nmyphp/article/details/79174225

**Comment by lovepoem** [comment]
>我在kryo基础上还加入了twitter chill，支持Java的同时，还能比较完美的支持Scala，让Scala童鞋也能享受dubbo直接支持数据类型的快感，如何分享

@superleo-cn ,can you give your code repository?

**Comment by ldcsaa** [comment]
@lovepoem 现在的dubbo与当当的dubbox（2.8.4）应该是不兼容的吧？dubbox修改了dubbo的序列化协议。
\dubbo\rpc\protocol\dubbo\DubboCodec.java 对比：
image

**Comment by lovepoem** [comment]
>  \dubbo\rpc\protocol\dubbo\DubboCodec.java 对比：
你用的什么协议？ 如果是默认的hessian协议，还是支持的

**Comment by Bmg00** [comment]
terrymanu:master

**Comment by zhangruhong** [comment]
这是我的自动回复邮件。
This is an automatic reply of the email system.
您好，你的邮件我己收到，我会尽快处理，谢谢！I have received your E-mail, and I will reply as soon as possible. Thank you!

**Pull request merged**
