### PR TITLE
add codecov component #992 

### PR DESCRIPTION
**Pull request by lovepoem**
## What is the purpose of the change

#992  

## Brief changelog

update pom.xml
             .travis.yml

we can get:
the test coverage rate of the entire project
coverage rate change of every PR

### CODE REVIEW

**Comment by chickenlj** [comment]
Hello, lovepoem. Have u test this in your own repository?

**Comment by lovepoem** [comment]
Yes. https://github.com/lovepoem/codecov-travis-maven-test is a new repository I created three days ago for this issue .

Please see the examples:
https://github.com/lovepoem/codecov-travis-maven-test
lovepoem/codecov-travis-maven-test#3

dubbo code master should do：
login https://travis-ci.org/ and add dubbo repository to https://travis-ci.org/ (it seems done)
login https://codecov.io/ and add dubbo repository to https://codecov.io/

**Comment by chickenlj** [comment]
Is CodeCov necessary? I find many other github projects haven't integrate with CodeCov. 
Will it help us to figure out whether a PR has enough UT?

**Comment by lovepoem** [comment]
I think a rich test case is necessary for the quality of the code. Travis Ci and codecov were only popular in the last two years. Codecov does help us check every PR test code and improve the test code coverage.

**Pull request merged**
